### ISSUE TITLE
Add tests for constant-space NAR processing

### ISSUE THREAD

**Issue by imalsogreg** [haskell-nix/hnix-store#10]
When working with NARs that are large, we want to test that our serialization/deserialization can work in constant space. This can be achieved with a run of the test suite with RTS parameters limiting the heap size, e.g. `./space-tests +RTS -K100K`  (taken from http://neilmitchell.blogspot.com/2015/09/detecting-space-leaks.html)

@shlevy Could you add links to this ticket to issues in `nix` tooling where memory issues affected NAR processing? Those could suggest test fixtures and specific regression tests for us.

**Comment by shlevy** [comment]
There are a bunch...

https://github.com/NixOS/nix/issues/1988
https://github.com/NixOS/nix/issues/1969
https://github.com/NixOS/nix/pull/619
https://github.com/NixOS/nix/pull/1754
https://github.com/NixOS/nix/issues/1681
https://github.com/NixOS/nix/issues/1400
https://github.com/NixOS/nix/issues/358

and probably more.

**Comment by imalsogreg** [comment]
Thanks for the examples!

We now have constant-space streaming tests for large files in #7

**Comment by imalsogreg** [comment]
Closed by #7

**Comment by ryantrinkle** [comment]
Wow, this is awesome!  Thanks guys - just got bit by https://github.com/NixOS/nix/issues/1988

**Comment by nh2** [comment]
I made a PR that should fix (at least one more part) of that in nix: https://github.com/NixOS/nix/pull/2206
