### ISSUE TITLE
Lets do a new release

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#111]
@sorki Hello.

The cryptohash-sha512 situation got solved. Giving us some room to breathe.

WIth gaining access rights, and your worthy deps clean-up - I think we stabilized the project for the time. Until the GHC 9.0 releases.

The work done now, on publishing a release allows much simpler resolution of the Stackage, since cryptohash-sha512 revision should arrive there in parralel and you cleaned-up the deps that were holing the Stackage update. Which should solve Stackage and so the Nixpkgs situation.

After we resolved all these situations - a minor release would be a great way to stabilize the project.

I think the Stackage maintenance should be expanded. When/if you would feel like it - ping me, as an uninterested in power third party I would initiate the discussion. It is an official recommendation that the maintainer of the Hackage package to be the maintainer of the Stackage. I think that package was released to Stackage too early, but whatever - that is my opinion.

**Comment by sorki** [comment]
I agree and thanks for the removal of the overrides (coincidentally they were causing issues with building Haddocs). 

I've started a clean-up pass to get rid of the warnings but had to attend to other things. I would like to finish that one and we can do the release and figure out the Stackage situation - I think it's just a matter of listing multiple people for our packages or even whole organization since we already get pings to `@haskell-nix` (I'm not sure where these land tho).

**Comment by Anton-Latukha** [comment]
> had to attend to other things

That is "Of course".

> Stackage situation

I do not have any exp with Stackage. I just guessed that here we had a management bottleneck here - there is from all evidence is also a bottleneck.

My own opinion:
  * That Stackage publish was a false-start. Projects are still under heavy development, Stackage is all about stability & reverse-compatibility, & our projects break that with every release. Our projects are still forming, the APIs are constantly changing. If we go Stackage - we would need to support backward compatibility, or deal with Stackage freezes for stability and that causes additional problems & maintenance in the Nixpkgs.

  * And after all - what is the point of publishing 1 of 3 interlinked projects to the Stackage - to stuck divided in the middle between Hackage, Stackage & Nixpkgs?
  * Since 3 projects are interlinked and evolve together - they all at once should not be on Stackage - or all 3 go and support Stackage at once. And my own opinion - it still looks just a bit too early for that. HNix only now arrives at completing the core base of features, so to say - stability. & Especially before the HNix splitting into packages, Stackage and Nixpkgs dependency on it - it would complicate the splitting process, splitting in itself is already a big process that would pack a lot of much more important stuff, like whole API {reshuffle, clean-up, migration help}.
I'd voted to hold horses on Stackage. But also trying to allow more people, throwing ... "resources" on it, sort to say, is also a universal way.
Indeed, maybe if there were 6 people with access to the Stackage package - the situation probably'd resolved much faster.
