### ISSUE TITLE
tasty-discover missing from nix-shell env

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix-store#127]
Hacked around it in `shell.nix` with

``` 
libraryHaskellDepends = external-inputs ++ [ pkgs.haskellPackages.tasty-discover ];
```

Properly it should go into `libraryHaskellDepends` using `overrideCabal` in `overlay.nix` so `shell.nix` can pick it up.

**Comment by Anton-Latukha** [comment]
Well, I thought the `overlay` extension of Nix derivations with `tasty-discover`, *idk* what is going on.

**Comment by sorki** [comment]
It's due to the way how `shell.nix` is done - it takes all Haskell deps from both packages using `getHaskellBuildInputs`

```
  # Extract the haskell build inputs of a haskell package.
  # This is useful to build environments for developing on that
  # package.
  getHaskellBuildInputs = p: (getBuildInputs p).haskellBuildInputs;
```

so it ignores `buildInputs` added in overlay.

**Comment by peti** [comment]
Actually, I think the missing dependency should be declared in the Cabal file so that cabal2nix can generate a proper Nix expression from the get-go.

**Comment by Anton-Latukha** [comment]
But that would solve only the Nix case, that would not solve the Hackage case, it would add a dependency that Cabal builds would report unused.

**Comment by peti** [comment]
Add it as a build tool dependency for the test suite. That will make both cabal and nix happy.

**Comment by Anton-Latukha** [comment]
Thanks for pointing how it does in Nixpkgs and to where to look in Cabal. I was searching in both places.

Adding it into `build-tool-depends` is a proper solution, it fixes everything.
Opened report to mention that, probably need to open PR myself.

Done:
```
[nix-shell:~/src/haskell/hnix-store]$ command -v tasty-discover
/nix/store/4rkdwpn6srjgmhclhhjpada6shf4fvfw-ghc-8.10.3-with-packages/bin/tasty-discover

```
