### ISSUE TITLE
Please, fix Remote build for `darwin`

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#141]
Just to note.

Currently, HNix-Store-Remote requires `linux-namespaces`, so the build falls flat for macOS.

Since HNix CLI uses Remote - that breaks the executable on `darwin`.

**Comment by Anton-Latukha** [comment]
But, well, that is the way it goes.

**Comment by sorki** [comment]
Remote only needs `linux-namespaces` for tests so this shouldn't affect anything else. Also `io-testsuite` flag is disabled by default ~~but I think this is not picked up by `cabal2nix`~~. Nix package doesn't list it in deps either. Cabal build?

**Comment by Anton-Latukha** [comment]
Ah, yes. Indeed, you're right.

**Comment by soulomoon** [comment]
> Remote only needs `linux-namespaces` for tests so this shouldn't affect anything else. Also `io-testsuite` flag is disabled by default ~but I think this is not picked up by `cabal2nix`~. Nix package doesn't list it in deps either. Cabal build?

Is that darwin have equivalent to linux-namespaces ?
If it does, I will try to implement so I can dev in  darwi.

**Comment by sorki** [comment]
> > Remote only needs `linux-namespaces` for tests so this shouldn't affect anything else. Also `io-testsuite` flag is disabled by default ~but I think this is not picked up by `cabal2nix`~. Nix package doesn't list it in deps either. Cabal build?
> 
> Is that darwin have equivalent to linux-namespaces ? If it does, I will try to implement so I can dev in darwin.

I'm not aware of such equivalent - probably best to use virtual machine or CI as the testsuite creates a temporary nix store and runs privileged nix-daemon as pid 0 in a namespace.

**Comment by soulomoon** [comment]
Sure, guess that what I can do. 

Currently using docker with vscode.
But ownership problem hassles me.
Try it latter times when I got a virtual machine setup.


```
[nix-shell:/workspaces/hnix-store]# cabal v2-run "test-suite:hnix-store-remote-tests"
Up to date
error: changing ownership of path '/tmp/test-nix-store-360cdb1d06f295c6/store': Invalid argument
tests/Spec.hs
  protocol
    store
      syncWithGC
        syncs with garbage collector: accepted connection from pid 19525, user root (trusted)
error: changing ownership of path '/tmp/test-nix-store-e5f5b6e59ef54a25/store': Invalid argument
OK (0.24s)
```
