### ISSUE TITLE
Drop `StorePathSet` type alias in favor of `HashSet StorePath`

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix-store#146]
It was pointed to me before that these are not very useful and actually getting in the way of refactoring, e.g. turning `StorePathMetadata` into polymorphic `Metadata a` requires turning the `references` field into `HashSet a`.

**Comment by Anton-Latukha** [comment]
Seems reasonable to reduce it.

**Comment by sorki** [comment]
Done via #230
