### ISSUE TITLE
GADT for store protocol

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix-store#149]
Scratch design of protocol `GADT`, with the intention of it being polymorphic in `path` type and its interpreters.

```haskell
data Store (path :: Type) (m :: Type -> Type) (a :: Type) where
  QueryPathMetadata 
    :: path
    -> Store path m (Metadata path)

  AddText
    :: TextName
    -> TextBody
    -> HashSet path  -- ^ References
    -> Store path m path

-- Store (StorePath @"/nix/store")
```

My current idea is turning the current `-remote` protocol mess into `hnix-store-protocol` which would only contain `GADT` and then add interpreters for client/server that would both use the same core type.

Feedback much appreciated!

**Comment by Anton-Latukha** [comment]
My feedback: "I do not have profficiency in this to recommend anything 8)".

**Comment by soulomoon** [comment]
What not do polymorphic over typeclass as in hnix. Seems two projects's style differs a great deal.

**Comment by sorki** [comment]
> GADT does seems to make the code cleaner in this case.
> and futher do polymorphic over typeclass as in hnix too.
> Seems two projects's style differs a great deal.

Good point. There's already some wrapping due to this although the subset used by hnix is pretty small at the moment. Adopting tagless style with typeclass is probably a better idea.

**Comment by sorki** [comment]
:tada:

**Comment by sorki** [comment]
> GADT does seems to make the code cleaner in this case. and futher do polymorphic over typeclass as in hnix too. Seems two projects's style differs a great deal.

Aligned a lot!
