### ISSUE TITLE
Please, import the Core from Hackage for Remote

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#164]
Continuation of: #159

After the https://github.com/haskell-nix/hnix-store/releases/tag/core-0.5.0.0 the #161 shown the https://github.com/haskell-nix/hnix-store/pull/161/checks?check_run_id=2794535505, which is https://github.com/haskell-nix/hnix-store/pull/161#issuecomment-858700296.

In other words:
>  we meet another constraint of the CI - the Core 0.5 release happened, but it is not yet imported into Nixpkgs.

I debate the need of having the Nixpkgs import of Core for Remote, as we have Haskell development here.

The proper way - is to import the Core from the Hackage for Remote.

At that, maybe introduce a switch if people want to work cross-project simultaneously.

**Comment by Anton-Latukha** [comment]
Well, I see a problem to investigate & solve, `callHackage` asks for a release version.

**Comment by Anton-Latukha** [comment]
One of possible solutions can be downloading latest tarball from Hackage and running `haskellSrc2nix` on it.
But somehow Hackage does not *seem* to provide the static URL to download *the latest* release.

Sources: http://neilmitchell.blogspot.com/2018/11/downloading-all-of-hackage.html

**Comment by expipiplus1** [comment]
You might be interested in `callHackageDirect`, you can see how I use it here: https://github.com/expipiplus1/vulkan/blob/9dad2201bfe385ce0d791fc3593e8ef455f131ed/nix/haskell-packages.nix#L119-L123

**Comment by Anton-Latukha** [comment]
Yes. It has a problem, two actually, - they are called fields "version" & "sha256".
It is not "an automatic testing", if at every sneeze it needs a manual rebasing.

Can your project solve this kind of thing?

**Comment by expipiplus1** [comment]
sadly it only updates the sha256 hash and not version, probably nothing stopping it doing version too though...

**Comment by Anton-Latukha** [comment]
I'm actually surprised Nixpkgs codebase does not provide both variants, fixed & unfixed importing. Having a rolling expressions always seems a legit strut to me in many scenarios. It has not got traction probably just because code is Nixpkgs code & Nixpkgs deprecates not Nixpkgs ways & not thinks much about the use of the code externally. But also if expression can be updated in 1 command - that is even a better way. I still need to learn your tool.

**Comment by sorki** [comment]
I've tried but it creates too much overhead to be practical. Especially weird for drive-by contributors who would need to split the PRs, wait for releases, then create another PRs, wait for more releases. This defies the point of having a monorepo with multiple sub-packages and tries to solve a non-issue.
