### ISSUE TITLE
Current `addToStore` API from hnix-store is too limited, we should shape it

### ISSUE THREAD

**Issue by soulomoon** [haskell-nix/hnix-store#176]
To implement `fetchurl`  in hnix, haskell-nix/hnix#1050, haskell-nix/hnix#1051.

We need to perform the following.
Dowload the file content -> dump file content to nar -> Add the nar to remote store.

But in current `addToStore` api of hnix-store we can just send local file to daemon

**Comment by soulomoon** [comment]
Current  `addToStore` api in nix-store just support local file path while the `addToStore` should also support send string to daemon. Abstracting contetnt source to `Source` as is [nix Implementation under remote store](https://github.com/NixOS/nix/blob/97e02c23bde0515540c63081824f85ff1cebd86f/src/libstore/remote-store.cc#L592).

**Comment by soulomoon** [comment]
We can dumpString to nar like this. 
```
dumpString 
  :: forall m
   . (MonadIO m)
  => (ByteString -> m ()) -> ByteString -> m ()
dumpString yield text = do
  yield $ str "nix-archive-1"
  parens $ (do 
    yield $ str "type" 
    yield $ str "regular"
    yield $ str "contents"
    yield $ str text)
  where 
    str :: ByteString -> ByteString
    str t =
      let
        len = BL.length t
      in
        int len <> padBS len t
    int :: Integral a => a -> ByteString
    int n = Serial.runPut $ Serial.putInt64le $ fromIntegral n
    padBS :: Int -> ByteString -> ByteString
    padBS strSize bs = bs <> BL.replicate (padLen strSize) 0
    parens act = do
      yield $ str "("
      r <- act
      yield $ str ")"
      pure r
```

**Comment by soulomoon** [comment]
The current implementation of `addToStore` in hnix is actually partially corresponding to `RemoteStore::addCAToStore` in nix

**Comment by soulomoon** [comment]
I have a draft about this.

In order to do it we can replace the filepath argument in `addToStore` with a more common type `type NarSource m =  (ByteString -> m ()) -> m ()`. 
* `FilePath` can turn to `NarSource m`.
* `Text` can turn to `NarSource m`

**Comment by sorki** [comment]
Nice, the remote store API was built against an older nix-store version so some things are a bit dated/different in nix. Feel free to adjust as needed.

**Comment by soulomoon** [comment]
@sorki Thank for the replies. It should now be ready to run the github workflows, awaiting approval. Please approve to run the workflow and review it.
