### ISSUE TITLE
Construct hnix-store configuration from hnix settings

### ISSUE THREAD

**Issue by shlevy** [haskell-nix/hnix-store#19]
Figure out appropriate design for hnix-store configuration and mapping from hnix settings (for choosing backend, configuring backend where relevant)

**Comment by Anton-Latukha** [comment]
I think it is a bluesky at this point. If no one would do Nix configuration integration between projects - it never would be done.

After current work done, for a 1.5 year there is not that much configuration trouble in the first place here.
