### ISSUE TITLE
Switch to `crypton`

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix-store#239]
- https://hackage.haskell.org/package/crypton
- https://github.com/kazu-yamamoto/crypton

Never-ending crypto story!

**Comment by Ericson2314** [comment]
https://github.com/haskellfoundation/tech-proposals/blob/main/proposals/052-cryptography-leg-1.md this is hopefully the end of the crypto story :)

**Comment by sorki** [comment]
So this might not be worth doing right away but also should be quite easy as they are compatible. According to the proposal the botan based one will have `Cryptonite` compat layer so we might just wait for that and skip the intermediate switch to `crypton`.

Also not really a pressing issue at all.
