### ISSUE TITLE
Steal signature tests from tvix-compat

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix-store#240]
https://cl.tvl.fyi/c/depot/+/10081/1/tvix/nix-compat/src/narinfo/signature.rs

With proper attribution to @flokli!

This might allow us to deal with saltine vs cryptonite/crypton conundrum.

**Comment by flokli** [comment]
The credit also goes to @zimbatm, the fixture was produced as part of https://github.com/nix-community/go-nix/pull/93.

**Comment by zimbatm** [comment]
This kind of stealing is good!
