### ISSUE TITLE
Implement SRI hash parsing/printing

### ISSUE THREAD

**Issue by shlevy** [haskell-nix/hnix-store#30]
https://github.com/NixOS/nix/commit/6024dc1d97212130c19d3ff5ce6b1d102837eee6

**Comment by shlevy** [comment]
cc @imalsogreg

**Comment by bqv** [comment]
N.B. The old type:hash format doesn't currently work either?

**Comment by Anton-Latukha** [comment]
Solved in [System.Nix.Internal.Hash](https://github.com/haskell-nix/hnix-store/blob/72eaf6c01dbbc05970b9efe3d54fb7bd32f9214b/hnix-store-core/src/System/Nix/Internal/Hash.hs#L105)

`mkNamedDigest` parses SRI hash into `SomeNamedDigest` which has `Show` instance.
