### ISSUE TITLE
Investigate using cryptohash-sha256 instead of cryptonite

### ISSUE THREAD

**Issue by mightybyte** [haskell-nix/hnix-store#4]

**Comment by imalsogreg** [comment]
I believe we lose 2 things by moving to `cryptohash-sha256`, and that the benefit we get from them doesn't justify the cost of using `cryptonite`:

 - Type-level tracking of the hash algorithm. There are a limited number ( < 10 ) of ways that hashes are computed, and we can just have a newtype wrapper for each. Or steal the `Digest` type family from `cryptonite`.
 - Base32 encoding of a sha256 digest. I'm not sure how maintained the [base32-bytestring](https://hackage.haskell.org/package/base32-bytestring) library is, plus nix uses its own unique character mapping (it's incompatible with `cryptonite`'s, but we could probably Caesar-cypher between the two)... so maybe we shoud just implement that ourselves, [as nix does](https://github.com/NixOS/nix/blob/master/src/libutil/hash.cc#L61).  To get a gist of what this would look like, see my [cryptohash-256 branch of hnix-store](https://github.com/imalsogreg/hnix-store/compare/master...imalsogreg:cryptohash-256), where I've gotten started trying to do that. No testing or careful thought about corner cases has been done yet, WIP.

**Comment by imalsogreg** [comment]
We gain a smaller dependency footprint (`basement`, `foundation`, `memory` and `cryptonite` go away). I'm not sure if truncation is a formally defined thing, or simply means "take all but the last N bytes" - do you expect it to be hard?

**Comment by shlevy** [comment]
Nah, not hard, just was pleasantly surprised at how straightforward and generic the cryptonite version is. Anyway, happy to accept a PR switching

**Comment by domenkozar** [comment]
Relevant: https://github.com/vincenthz/hs-memory/issues/67

**Comment by imalsogreg** [comment]
Closed by #27
