### ISSUE TITLE
Make sure README always builds

### ISSUE THREAD

**Issue by Ericson2314** [haskell-nix/hnix-store#47]
Let's do https://github.com/obsidiansystems/aeson-gadt-th/blob/develop/aeson-gadt-th.cabal#L26-L34 does so the README actually builds:
```cabal
executable readme
  build-depends: base, ...
  default-language: Haskell2010
  main-is: README.lhs
  ghc-options: -pgmL markdown-unlit -Wall
build-tool-depends: markdown-unlit:markdown-unlit
```
`README.lhs` is a symlink like https://github.com/obsidiansystems/aeson-gadt-th/blob/develop/README.lhs .

**Comment by shlevy** [comment]
Sounds good to me!

**Comment by sorki** [comment]
Thanks for the tip!!
