### ISSUE TITLE
README links to a dead location

### ISSUE THREAD

**Issue by ndmitchell** [haskell-nix/hnix-store#49]
https://github.com/haskell-nix/hnix-store/tree/master/hnix-store-core links to https://github.com/haskell-nix/hnix-store/blob/master/hnix-store-core/src/System/Nix/Store.hs which is a 404.

**Comment by shlevy** [comment]
Argh yeah I'm in the midst of a refactor/cleanup. Store.hs will be restored "soon"

**Comment by Anton-Latukha** [comment]
Thanks Neil for giving a note.
