### ISSUE TITLE
Nar uses lazy IO instead of streaming

### ISSUE THREAD

**Issue by domenkozar** [haskell-nix/hnix-store#51]
Feed it a store path with lots of files and you end up with:

```
/nix/store/3m1hc2mrz6zhqng088s4fw0rzfb1g6qy-perl-5.28.1: getDirectoryContents:openDirStream: resource exhausted (Too many open files)
```

**Comment by roberth** [comment]
The culprit: https://github.com/haskell-nix/hnix-store/blob/master/hnix-store-core/src/System/Nix/Nar.hs#L81-L88

One may also consider [`unix`'s bytestring directory functions](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Directory-ByteString.html), to match Nix more closely. For performance, it's best to [`getFileStatus`](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Files-ByteString.html#v:getFileStatus) once per path.

**Comment by shlevy** [comment]
@imalsogreg Are you able to take a look?

**Comment by imalsogreg** [comment]
Yeah - thanks for the analysis on this. I'll try to reproduce with a test and then fix with some combination of [streaming](http://hackage.haskell.org/package/streaming) and [unix](http://hackage.haskell.org/package/unix). Will update the ticket when I have a WIP branch.

**Comment by domenkozar** [comment]
Relevant: https://github.com/haskell-nix/hnix-store/pull/52

**Comment by domenkozar** [comment]
Hey @imalsogreg did you make some progress on this one?

**Comment by imalsogreg** [comment]
@domenkozar Nope, attention's been elsewhere, but thanks for the bump.

**Comment by domenkozar** [comment]
I'm happy to sponsor $150 for someone fixing this issue.

**Comment by imalsogreg** [comment]
@domenkozar I've been focusing on this the past couple days, on the `vigorous-io` branch.

**Comment by sorki** [comment]
Closing since this landed some time ago, it could use some real world testing! :smile:
