### ISSUE TITLE
GHC 8.8.1

### ISSUE THREAD

**Issue by domenkozar** [haskell-nix/hnix-store#54]
regex-tdfa-text needs a bump (or need to pick a different regex library ).

**Comment by domenkozar** [comment]
Ah it's deprecated: `Deprecated. in favor of regex-tdfa`

**Comment by dhess** [comment]
@domenkozar Easy peasy, see #55 

Note that you'll need to build `hnix` from git, as the most recent Hackage version also has a `regex-tdfa-text` dependency.

**Comment by domenkozar** [comment]
Thanks :)
