### ISSUE TITLE
A new release for hnix-store-core?

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix-store#56]
The latest version of hnix-store-core on Hackage (v0.1.0.0) is unbuildable with GHC 8.8, whereas `master` builds fine. Could you make a new release?

**Comment by imalsogreg** [comment]
Sounds good to me. @shlevy if you make me a comaintainer on Hackage, I can push 0.2.0.0

**Comment by shlevy** [comment]
What do I need to do?

**Comment by imalsogreg** [comment]
@shlevy to add a maintainer on Hackage, go to https://hackage.haskell.org/package/hnix-store-core/maintainers/edit

**Comment by shlevy** [comment]
Done

**Comment by imalsogreg** [comment]
Pushed it up: https://hackage.haskell.org/package/hnix-store-core

**Comment by sjakobi** [comment]
Many thanks! :)

PR for hnix is here: https://github.com/haskell-nix/hnix/pull/537

**Comment by sorki** [comment]
Now `regex-tdfa-text` is marked as broken in `haskell.packages.ghc882`.  #59 removes regex dependencies completely.

**Comment by bqv** [comment]
@shlevy @imalsogreg Ditto for hnix-store-remote, or would you like me to open a new issue?

**Comment by sorki** [comment]
@bqv was on my TODO list, see #76
