### ISSUE TITLE
Missing haddocks for hnix-store-core on Hackage

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix-store#65]
Here's the build report: http://hackage.haskell.org/package/hnix-store-core-0.2.0.0/reports/2

To fix the issue, you could upload the documentation manually, just like the `saltine` maintainer did.

**Comment by sjakobi** [comment]
Upstream issue for Hackage: https://github.com/haskell/hackage-server/issues/882

**Comment by Anton-Latukha** [comment]
Someone with the access to the project on Hackage:

Please, generate & upload the docs:
```shell
set -e

dir=$(mktemp -d /tmp/dist-docs.XXXXXX)
trap 'rm -r "$dir"' EXIT

# assumes cabal 2.4 or later
cabal v2-haddock --builddir="$dir" --haddock-for-hackage --enable-doc

# (pasting pass does not work) Enter _by hand_: account, password
cabal upload -d --publish $dir/*-docs.tar.gz
```

Or as it put at the bottom of the https://hackage.haskell.org/upload.
