### ISSUE TITLE
Add hnix-store-core to Stackage?

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix-store#68]
I'd like to put `hnix` on Stackage (https://github.com/commercialhaskell/stackage/pull/5429), mostly to simplify installation for `stack` users.

Would you consider adding `hnix-store-core` to Stackage? You can find instructions [here](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by sjakobi** [comment]
FWIW, `saltine` with its `libsodium` system dependency is already on Stackage: https://www.stackage.org/package/saltine

**Comment by Anton-Latukha** [comment]
`hnix-store-core` was released to Stackage Nightly, now we have #104.
