### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix-store#76]
We can start preparing 0.3 release at this point, there's only #72 pending which should probably make it in as it's required for further hnix/hnix-store integration.

- [x] Update changelogs
  - [x] Nar streaming for -core 
  - [x] Removal of `addToStoreNar` for -remote
- [x] Tag
- [x] Upload to hackage
- [x] Create GitHub release

**Comment by layus** [comment]
I think we should skip #72 for now and release without it. There is a big overhaul needed to change the monad stack. And it is nowhere close to be over.
(Plus I need a 0.3 release for https://github.com/haskell-nix/hnix/pull/554 :-))

**Comment by sorki** [comment]
I've tagged bc10465de23dcffce8d93e39204d4c6bd84d7d6a as 0.3.0.0.

Should be good for release I think.

@imalsogreg can I bother you to upload `-core` to Hackage? I'll upload `-remote` right after.

Uploading docs manually shouldn't be needed anymore.

**Comment by sorki** [comment]
Oops, noticed that Changelog still needs setting release date and removing unreleased.

**Comment by imalsogreg** [comment]
@sorki 👍  Uploaded -core 0.3.0.0 to hackage.

**Comment by imalsogreg** [comment]
Oh no, I see the ChangeLog for -core needs updating too. Are you fixing both?

**Comment by sorki** [comment]
Yup, both fixed in #78. Sorry about that.

**Comment by sorki** [comment]
Both released :tada:  Thank you all!

**Comment by imalsogreg** [comment]
🎉   Great work @sorki !
