### ISSUE TITLE
NAR serialization code

### ISSUE THREAD

**Issue by adnelson** [haskell-nix/hnix-store#8]
(Originally posted on the `hnix` issues page)

I have code for serializing and deserializing NARs and "exported" NARs (including metadata) that I reverse engineered from the C++ implementation a while ago. It currently lives here: https://github.com/adnelson/nix-binary-cache/blob/master/src/Nix/Nar/Serialization.hs 
I'm not sure if this already being worked on, or where it would fit into the code if we wanted it here, but I'd be happy to merge them into this one.

**Comment by shlevy** [comment]
cc @imalsogreg

**Comment by imalsogreg** [comment]
@adnelson Thanks for pointing it out - I wish I'd know about your serialization code earlier :) I'm working on the same in this PR https://github.com/haskell-nix/hnix-store/pull/7  - Do you have any ideas about laziness issues Shea mentioned in PR comments?
