### ISSUE TITLE
Skip or fix tests in nix-like sanboxes

### ISSUE THREAD

**Issue by layus** [haskell-nix/hnix-store#80]
Some hnix-store-remote tests do not work in sandboxes because of _reasons_. I think the use of namespaces, or possibly opening a socket is a problem.

We should make these tests sandbox-friendly, or skip them so as to make the test pass in this setup.

Also related to a proper hnix-store ci :-)

**Comment by sorki** [comment]
I've added `io-testsuite` flag recently (https://github.com/haskell-nix/hnix-store/blob/master/hnix-store-remote/hnix-store-remote.cabal#L16) to remedy this but testing the build it looks like it's ignored. Not sure why.

**Comment by layus** [comment]
Well, it is just explicitly turned on in https://github.com/haskell-nix/hnix-store/blob/04444ce5e14320d955e6a3ffa054e7cdcced1b81/overlay.nix#L5. We could change that in hnix. Just override the set of flags.

**Comment by sorki** [comment]
Ah thanks. I didn't notice you use overlay from here. `dontCheck` is fine for now or I can disable the flag in the overlay and just enable it for shell / local build.

Like this will go away with the nixpkgs PR fixing `cryptohash-sha512` and being able to use both from nixpkgs. Trying to figure out what's going on I've manage to update both in nixpkgs and noticed missing extra files for `-core`.

Alternatively we can enable tests in hnix, the only requirement is `nix` (`nix-daemon`) being present so harness can setup temporary environment. Will take a look.

**Comment by layus** [comment]
Found a workaround for now https://github.com/haskell-nix/hnix/pull/554/files#diff-245563af9e34754739b12b294f3324c1d42c116ace7ce8735e21dfbc82d8e064R232-R235

**Comment by Anton-Latukha** [comment]
Topic was fixed by `sorki` in #59 and already released and it is already used in the CI.
All discussed in the topic currently is done.
