### ISSUE TITLE
Please, upload docs to Hackage

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#82]
Someone with the access to the project on Hackage:

Please, generate & upload the docs:
```shell
set -e

dir=$(mktemp -d /tmp/dist-docs.XXXXXX)
trap 'rm -r "$dir"' EXIT

# assumes cabal 2.4 or later
cabal v2-haddock --builddir="$dir" --haddock-for-hackage --enable-doc

# (pasting pass does not work) Enter _by hand_: account, password
cabal upload -d --publish $dir/*-docs.tar.gz
```

Or as it put at the bottom of the https://hackage.haskell.org/upload.

**Comment by Anton-Latukha** [comment]
For additional information, Hackage platform build process are somewhat differs from the local build, and has problems with generating docs when some system dependency is used, AFAIK it was particularly `saltine` dependency on `libsodium` in our case. Until they resolve this issue upstream, releases would always require manual documentation upload afterwards of the release.

**Comment by sorki** [comment]
`libsodium` should be fine since https://github.com/haskell/hackage-server/issues/882 but `cryptohash-sha512` is a problem now for `hnix-stores` and soon `hnix` as well so back to manual uploads.

**Comment by Anton-Latukha** [comment]
Moving info & closing in favor of https://github.com/haskell-nix/hnix-store/issues/65
