### ISSUE TITLE
Please, migrate from deprecated `cryptohash*` to new shiny `cryptonite*`

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#83]
Trues with `cryptohash` is simple - it got deprecated and superseded: https://github.com/vincenthz/hs-cryptohash#readme - that banner was added there 5 years ago.
And points to `cryptonite`, which family ships all kinds of hashing, & the SHA512 also, or also known as SHA-2.
https://hackage.haskell.org/package/cryptonite
```
Crypto.Hash
    Crypto.Hash.Algorithms
```
Contains SHA512 also.

**Comment by sorki** [comment]
Ad `cryptohash` deprecation -  https://github.com/dhall-lang/dhall-haskell/pull/1822#issuecomment-636333155

See also #66

I don't think it's worth putting work into this due to one package with outdated bounds, PRs welcome tho.

**Comment by Anton-Latukha** [comment]
With a caveat that HVR does not maintain it, which created a problem.

BTW, since people can not reach him, I wrote to him about it yesterday, but then saw `hs-cryptohash` banner, so sequentially send "Oh, nevermind". But now it came out I was kind-of right about writing to him, except that `cryptonite` trully superseded it.

**Comment by Anton-Latukha** [comment]
Yesterday I tried to - migration essentially means by adding the lib the rooting-out/throwing-out/rewriting the Internal/Hash.hs. Which is a pretty small sizable effort. If only I knew which interface is really needed. Maybe someone with higher skill would find even a smaller way to migrate, but `Cryptonite` hides the `Digest` constructor - it only accessible through functions, and the constructor was needed to `finalize` into Store code manually. Current Hash.hs essentially duplicates the library code, and adds a possibility of handling the Truncated hash. Upstreaming into the library the Truncated hash mode would allow to make Hash.hs almost/nonexistent, but also truncation of course can happen on top of hashes.

**Comment by Anton-Latukha** [comment]
I decided to reformulate the report theme.
