### ISSUE TITLE
Please, form a new release

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#85]
The fix release would allow to merge the https://github.com/haskell-nix/hnix/pull/554.

**Comment by Anton-Latukha** [comment]
Last 2 releases on Hackage were broken:
https://matrix.hackage.haskell.org/#/package/hnix-store-core
https://matrix.hackage.haskell.org/#/package/hnix-store-remote

Remote fails because of wrong bounds on the Hackage HNix-Core, since HNix-Core in release allows but does not support `base16-bytestring` >= 1.
  
Recently I migrated Core to the `base16-bytestring >= 1` - but that is in master - Core release would fix the Remote Core dependency build.

Please make a Core release, then check the Remote and make its release.

Thank you.

**Comment by Anton-Latukha** [comment]
Remote also in the Nixpkgs marked broken.
AFAIK it was marked as such at least quite often if not continuously.

Now project has some basic CI testing. The `master` of Core and Remote are fixed, and their release should fix it.

After that - there would be a sense in marking Remote as normal in Nixpkgs.

Related: https://github.com/haskell-nix/hnix-store/pull/95#issuecomment-749704053

**Comment by sorki** [comment]
Drafted new one at #103 

Do we want #93 included as well?

**Comment by Anton-Latukha** [comment]
> Do we want #93 included as well?

Nah.
That refactor is a bore, it is just some steps to be in-between closer to the full one.

**Comment by Anton-Latukha** [comment]
:partying_face:  https://hackage.haskell.org/package/hnix-store-core

**Comment by sorki** [comment]
I think I've found a Hackage bug in the process as I've initially uploaded `master` just to realize I wanted a commit before to not have `next` changelog entries there but subsequent candidate uploads nor final `--publish` didn't correct it.

**Comment by Anton-Latukha** [comment]
Maybe publish a new minor point release?

@sorki Please, notify us when the release would resolve.

**Comment by sorki** [comment]
I think it's fine, there's just little extra content in https://hackage.haskell.org/package/hnix-store-core-0.4.0.0/changelog 

Not worth another round.

**Comment by Anton-Latukha** [comment]
Oh - do not worry. Happens all the time. I made the same mistake last release or so :laughing:

I see the `HNix-Store-Core 0.4` already compiles: https://github.com/haskell-nix/hnix/pull/785/checks?check_run_id=1628083481, cheers.

Sorry if bothered you in any way in the holidays before NY.

**Comment by Anton-Latukha** [comment]
Looked into Nixpkgs.

* Core seems to be in the normal state there.
* Made `dontCheck self.cryptohash-sha512`, since I know that the upstream is stale and its test suite is incompatible with `base16-bytestring`, while our patched version is compatible - so aligned that in the Nixpkgs.
* Took Remote away from the broken list, and because its test suite AFAIK requires network access rights, and is not enabled by default - added `dontCheck self.hnix-store-remote`.

So, probably Nixpkgs are dealt with.

Pety AFAIR said would merge even on/around New Years.
