### ISSUE TITLE
Please, register and add Cachix to the CI Nix builds

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#96]
Currently the page with the creation of the cache for the project: https://app.cachix.org/cache

Does not work for me - the "Create" button is disabled.

Maybe it is site working weird in my case, maybe due to some 1 free project cache/user, maybe disabled new caches creations due to something, maybe, maybe, maybe...

The algorithm is quite straight-forward:

1. [x] Create Cachix account.
2. [x] Create Open Source Public binary cache.
3. [x] Get & save the authentication information.
4. [x] Set the authentication token/secret in the GitHub project Settings -> Secrets
5. [x] Add the cachix cache into CI Nix builds, the example is in HNix.
6. [x] Remove/reduce the GitHub file-based caching in those builds.
7. [x] Check that it works in the PR build.

**Comment by sorki** [comment]
Registered a cache - https://app.cachix.org/cache/hnix-store

Can't move further as I don't have access to Settings tho.

**Comment by Anton-Latukha** [comment]
Try now :wink:

**Comment by sorki** [comment]
Can access Settings but not enuf perms to access Secrets /o\

**Comment by Anton-Latukha** [comment]
Strange choice, GitHub. Secrets can not be viewed.

**Comment by sorki** [comment]
Added `CACHIX_SIGNING_KEY` to Secrets.

**Comment by sorki** [comment]
Also disabled `Require pull request reviews before merging` as I don't find it useful (neither `hnix` uses that).

**Comment by Anton-Latukha** [comment]
> Also disabled `Require pull request reviews before merging` as I don't find it useful (neither `hnix` uses that).

Agree, definitely the right choice in the current situation.

---

Ok. Now would introduce Cachix into the `nix-build`.
